"""Major schema update: restructure all tables with new fields and relationships

Revision ID: 09454f9e86d7
Revises: cfc7e062c18e
Create Date: 2025-08-08 04:32:21.571600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09454f9e86d7'
down_revision: Union[str, Sequence[str], None] = 'cfc7e062c18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_sections',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=False),
    sa.Column('cabinet', sa.String(length=10), nullable=False),
    sa.Column('layer', sa.String(length=10), nullable=False),
    sa.Column('color', sa.Enum('RED', 'GREEN', 'BLUE', 'YELLOW', name='sectioncolor'), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('used_units', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor', 'cabinet', 'layer', 'color', name='unique_section_combination')
    )
    op.create_index(op.f('ix_storage_sections_id'), 'storage_sections', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.Enum('WITHDRAW', 'RETURN', 'CONSUMED', name='transactiontype'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('item_type', sa.Enum('PARTITION', 'LARGE_ITEM', name='itemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('partition_id', sa.String(length=255), nullable=True),
    sa.Column('large_item_id', sa.String(length=255), nullable=True),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=True),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_item_id'), 'transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_transactions_item_name'), 'transactions', ['item_name'], unique=False)
    op.create_index(op.f('ix_transactions_item_type'), 'transactions', ['item_type'], unique=False)
    op.create_index(op.f('ix_transactions_large_item_id'), 'transactions', ['large_item_id'], unique=False)
    op.create_index(op.f('ix_transactions_partition_id'), 'transactions', ['partition_id'], unique=False)
    op.create_index(op.f('ix_transactions_storage_section_id'), 'transactions', ['storage_section_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_name'), 'transactions', ['user_name'], unique=False)
    op.create_table('large_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('rfid_tag_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'WITHDRAWN', name='largeitemstatus'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['rfid_tag_id'], ['rfid_tags.id'], ),
    sa.ForeignKeyConstraint(['storage_section_id'], ['storage_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_large_items_id'), 'large_items', ['id'], unique=False)
    op.create_index(op.f('ix_large_items_item_id'), 'large_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_large_items_rfid_tag_id'), 'large_items', ['rfid_tag_id'], unique=False)
    op.create_index(op.f('ix_large_items_status'), 'large_items', ['status'], unique=False)
    op.create_index(op.f('ix_large_items_storage_section_id'), 'large_items', ['storage_section_id'], unique=False)
    op.create_table('partitions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('rfid_tag_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'WITHDRAWN', name='partitionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['rfid_tag_id'], ['rfid_tags.id'], ),
    sa.ForeignKeyConstraint(['storage_section_id'], ['storage_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partitions_id'), 'partitions', ['id'], unique=False)
    op.create_index(op.f('ix_partitions_item_id'), 'partitions', ['item_id'], unique=False)
    op.create_index(op.f('ix_partitions_rfid_tag_id'), 'partitions', ['rfid_tag_id'], unique=False)
    op.create_index(op.f('ix_partitions_status'), 'partitions', ['status'], unique=False)
    op.create_index(op.f('ix_partitions_storage_section_id'), 'partitions', ['storage_section_id'], unique=False)
    op.drop_index(op.f('ix_storage_slots_id'), table_name='storage_slots')
    op.drop_table('storage_slots')
    op.add_column('items', sa.Column('unit', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('image_content_type', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('items_name_key'), 'items', type_='unique')
    op.create_index(op.f('ix_items_manufacturer'), 'items', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.drop_column('items', 'max_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_manufacturer'), table_name='items')
    op.create_unique_constraint(op.f('items_name_key'), 'items', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('items', 'image_content_type')
    op.drop_column('items', 'image_filename')
    op.drop_column('items', 'unit')
    op.create_table('storage_slots',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('assigned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('storage_slots_pkey'))
    )
    op.create_index(op.f('ix_storage_slots_id'), 'storage_slots', ['id'], unique=False)
    op.drop_index(op.f('ix_partitions_storage_section_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_status'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_rfid_tag_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_item_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_id'), table_name='partitions')
    op.drop_table('partitions')
    op.drop_index(op.f('ix_large_items_storage_section_id'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_status'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_rfid_tag_id'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_item_id'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_id'), table_name='large_items')
    op.drop_table('large_items')
    op.drop_index(op.f('ix_transactions_user_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_storage_section_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_partition_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_large_item_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_storage_sections_id'), table_name='storage_sections')
    op.drop_table('storage_sections')
    # ### end Alembic commands ###
