"""Add rfid_tags and storage_slots tables

Revision ID: 1319a38b2604
Revises: a5670500f72a
Create Date: 2025-08-01 05:45:49.765101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1319a38b2604'
down_revision: Union[str, Sequence[str], None] = 'a5670500f72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_tags',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_tags_id'), 'rfid_tags', ['id'], unique=False)
    op.create_table('storage_slots',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_slots_id'), 'storage_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_slots_id'), table_name='storage_slots')
    op.drop_table('storage_slots')
    op.drop_index(op.f('ix_rfid_tags_id'), table_name='rfid_tags')
    op.drop_table('rfid_tags')
    # ### end Alembic commands ###
