"""Add total quanttiy for container stat

Revision ID: 359555f8be10
Revises: 7c0ed41b75d8
Create Date: 2025-09-22 01:14:26.810618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359555f8be10'
down_revision: Union[str, Sequence[str], None] = '7c0ed41b75d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_stats', sa.Column('total_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container_stats', 'total_quantity')
    # ### end Alembic commands ###
