"""Fix Item Table and Item Stat datatype and Nullable

Revision ID: 47a4bcfa95b9
Revises: eb48e669d99d
Create Date: 2025-11-02 01:05:49.466373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47a4bcfa95b9'
down_revision: Union[str, Sequence[str], None] = 'eb48e669d99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('container_stats', 'container_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('container_stats', 'total_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('container_stats', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=False)
    op.alter_column('item_stat_history', 'total_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('item_stat_history', 'total_capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('items', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('largeitem_stats', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('largeitem_stats', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=False)
    op.alter_column('partition_stats', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partition_stats', 'total_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partition_stats', 'partition_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partition_stats', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partition_stats', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=True)
    op.alter_column('partition_stats', 'partition_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('partition_stats', 'total_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('partition_stats', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('largeitem_stats', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=True)
    op.alter_column('largeitem_stats', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('item_stat_history', 'total_capacity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('item_stat_history', 'total_quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('container_stats', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=True)
    op.alter_column('container_stats', 'total_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('container_stats', 'container_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
