"""Add Stock Table for Item Table

Revision ID: 5041b3ea67d8
Revises: d694a5fc4005
Create Date: 2025-09-21 03:07:07.452632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5041b3ea67d8'
down_revision: Union[str, Sequence[str], None] = 'd694a5fc4005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_stocks',
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('total_item_weight', sa.Float(), nullable=True),
    sa.Column('partition_high', sa.Float(), nullable=True),
    sa.Column('partition_low', sa.Float(), nullable=True),
    sa.Column('partition_total_capacity', sa.Integer(), nullable=True),
    sa.Column('large_item_high', sa.Integer(), nullable=True),
    sa.Column('large_item_low', sa.Integer(), nullable=True),
    sa.Column('container_high', sa.Float(), nullable=True),
    sa.Column('container_low', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_item_stocks_item_id'), 'item_stocks', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_stocks_item_id'), table_name='item_stocks')
    op.drop_table('item_stocks')
    # ### end Alembic commands ###
