"""Initialize Database

Revision ID: 50f133519eaa
Revises: 
Create Date: 2025-08-13 00:14:52.703244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f133519eaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.Enum('PARTITION', 'LARGE_ITEM', 'CONTAINER', name='itemtype'), nullable=False),
    sa.Column('measure_method', sa.Enum('VISION', 'WEIGHT', name='measuremethod'), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_manufacturer'), 'items', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('rfid_tags',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_tags_id'), 'rfid_tags', ['id'], unique=False)
    op.create_table('storage_sections',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('cabinet', sa.String(length=50), nullable=False),
    sa.Column('layer', sa.String(length=50), nullable=False),
    sa.Column('color', sa.Enum('RED', 'BLUE', 'GREEN', 'YELLOW', name='sectioncolor'), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('used_units', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.Enum('WITHDRAW', 'RETURN', 'CONSUMED', name='transactiontype'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('item_type', sa.Enum('PARTITION', 'LARGE_ITEM', 'CONTAINER', name='itemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('partition_id', sa.String(length=255), nullable=True),
    sa.Column('large_item_id', sa.String(length=255), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=True),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=True),
    sa.Column('previous_weight', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('weight_change', sa.Float(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_container_id'), 'transactions', ['container_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_item_id'), 'transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_transactions_item_name'), 'transactions', ['item_name'], unique=False)
    op.create_index(op.f('ix_transactions_item_type'), 'transactions', ['item_type'], unique=False)
    op.create_index(op.f('ix_transactions_large_item_id'), 'transactions', ['large_item_id'], unique=False)
    op.create_index(op.f('ix_transactions_partition_id'), 'transactions', ['partition_id'], unique=False)
    op.create_index(op.f('ix_transactions_storage_section_id'), 'transactions', ['storage_section_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_name'), 'transactions', ['user_name'], unique=False)
    op.create_table('users',
    sa.Column('employeeId', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('employeeId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employeeId'), 'users', ['employeeId'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('rfid_tag_id', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('container_weight', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'WITHDRAWN', name='containerstatus'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['rfid_tag_id'], ['rfid_tags.id'], ),
    sa.ForeignKeyConstraint(['storage_section_id'], ['storage_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_index(op.f('ix_containers_item_id'), 'containers', ['item_id'], unique=False)
    op.create_index(op.f('ix_containers_rfid_tag_id'), 'containers', ['rfid_tag_id'], unique=False)
    op.create_index(op.f('ix_containers_status'), 'containers', ['status'], unique=False)
    op.create_index(op.f('ix_containers_storage_section_id'), 'containers', ['storage_section_id'], unique=False)
    op.create_table('large_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('rfid_tag_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'WITHDRAWN', name='largeitemstatus'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['rfid_tag_id'], ['rfid_tags.id'], ),
    sa.ForeignKeyConstraint(['storage_section_id'], ['storage_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_large_items_id'), 'large_items', ['id'], unique=False)
    op.create_index(op.f('ix_large_items_item_id'), 'large_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_large_items_rfid_tag_id'), 'large_items', ['rfid_tag_id'], unique=False)
    op.create_index(op.f('ix_large_items_status'), 'large_items', ['status'], unique=False)
    op.create_index(op.f('ix_large_items_storage_section_id'), 'large_items', ['storage_section_id'], unique=False)
    op.create_table('partitions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('storage_section_id', sa.String(length=255), nullable=False),
    sa.Column('rfid_tag_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'WITHDRAWN', name='partitionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['rfid_tag_id'], ['rfid_tags.id'], ),
    sa.ForeignKeyConstraint(['storage_section_id'], ['storage_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partitions_id'), 'partitions', ['id'], unique=False)
    op.create_index(op.f('ix_partitions_item_id'), 'partitions', ['item_id'], unique=False)
    op.create_index(op.f('ix_partitions_rfid_tag_id'), 'partitions', ['rfid_tag_id'], unique=False)
    op.create_index(op.f('ix_partitions_status'), 'partitions', ['status'], unique=False)
    op.create_index(op.f('ix_partitions_storage_section_id'), 'partitions', ['storage_section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partitions_storage_section_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_status'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_rfid_tag_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_item_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_id'), table_name='partitions')
    op.drop_table('partitions')
    op.drop_index(op.f('ix_large_items_storage_section_id'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_status'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_rfid_tag_id'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_item_id'), table_name='large_items')
    op.drop_index(op.f('ix_large_items_id'), table_name='large_items')
    op.drop_table('large_items')
    op.drop_index(op.f('ix_containers_storage_section_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_status'), table_name='containers')
    op.drop_index(op.f('ix_containers_rfid_tag_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_item_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_users_employeeId'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_user_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_storage_section_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_partition_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_large_item_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_container_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('storage_sections')
    op.drop_index(op.f('ix_rfid_tags_id'), table_name='rfid_tags')
    op.drop_table('rfid_tags')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_manufacturer'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
