"""Update Item Table to store image path instead

Revision ID: 714412f4dedf
Revises: 549633d5a450
Create Date: 2025-08-11 06:14:42.944522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '714412f4dedf'
down_revision: Union[str, Sequence[str], None] = '549633d5a450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.drop_column('items', 'image_filename')
    op.drop_column('items', 'image')
    op.drop_column('items', 'image_content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('items', 'image_path')
    # ### end Alembic commands ###
