"""Remove Item Stock Table add pratition Stat, largeitem stat and container stat to keep trakc of stock detail instead

Revision ID: 7c0ed41b75d8
Revises: 5041b3ea67d8
Create Date: 2025-09-22 00:45:44.561662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0ed41b75d8'
down_revision: Union[str, Sequence[str], None] = '5041b3ea67d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_stats',
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('container_item_weight', sa.Float(), nullable=True),
    sa.Column('container_weight', sa.Float(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('high_threshold', sa.Float(), nullable=True),
    sa.Column('low_threshold', sa.Float(), nullable=True),
    sa.Column('stock_status', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='stockstatus'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_container_stats_item_id'), 'container_stats', ['item_id'], unique=False)
    op.create_index(op.f('ix_container_stats_stock_status'), 'container_stats', ['stock_status'], unique=False)
    op.create_table('largeitem_stats',
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('high_threshold', sa.Integer(), nullable=True),
    sa.Column('low_threshold', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='stockstatus'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_largeitem_stats_item_id'), 'largeitem_stats', ['item_id'], unique=False)
    op.create_index(op.f('ix_largeitem_stats_stock_status'), 'largeitem_stats', ['stock_status'], unique=False)
    op.create_table('partition_stats',
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=True),
    sa.Column('partition_capacity', sa.Integer(), nullable=True),
    sa.Column('high_threshold', sa.Float(), nullable=True),
    sa.Column('low_threshold', sa.Float(), nullable=True),
    sa.Column('stock_status', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='stockstatus'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_partition_stats_item_id'), 'partition_stats', ['item_id'], unique=False)
    op.create_index(op.f('ix_partition_stats_stock_status'), 'partition_stats', ['stock_status'], unique=False)
    op.drop_index(op.f('ix_item_stocks_item_id'), table_name='item_stocks')
    op.drop_table('item_stocks')
    op.alter_column('items', 'manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('items', 'container_weight')
    op.drop_column('items', 'container_item_weight')
    op.drop_column('items', 'partition_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('partition_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('container_item_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('container_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('items', 'manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('item_stocks',
    sa.Column('item_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_item_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('partition_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('partition_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('partition_total_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('large_item_high', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('large_item_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('container_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('container_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('item_stocks_item_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('item_stocks_pkey'))
    )
    op.create_index(op.f('ix_item_stocks_item_id'), 'item_stocks', ['item_id'], unique=False)
    op.drop_index(op.f('ix_partition_stats_stock_status'), table_name='partition_stats')
    op.drop_index(op.f('ix_partition_stats_item_id'), table_name='partition_stats')
    op.drop_table('partition_stats')
    op.drop_index(op.f('ix_largeitem_stats_stock_status'), table_name='largeitem_stats')
    op.drop_index(op.f('ix_largeitem_stats_item_id'), table_name='largeitem_stats')
    op.drop_table('largeitem_stats')
    op.drop_index(op.f('ix_container_stats_stock_status'), table_name='container_stats')
    op.drop_index(op.f('ix_container_stats_item_id'), table_name='container_stats')
    op.drop_table('container_stats')
    # ### end Alembic commands ###
