"""Update high and low threshold as mandatory

Revision ID: 8c299ee19e19
Revises: 359555f8be10
Create Date: 2025-09-22 01:37:12.616745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c299ee19e19'
down_revision: Union[str, Sequence[str], None] = '359555f8be10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('container_stats', 'high_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('container_stats', 'low_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('largeitem_stats', 'high_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('largeitem_stats', 'low_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('partition_stats', 'high_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('partition_stats', 'low_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partition_stats', 'low_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('partition_stats', 'high_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('largeitem_stats', 'low_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('largeitem_stats', 'high_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('container_stats', 'low_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('container_stats', 'high_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
