"""Update ItemStatHistory table reference item id

Revision ID: 8c501dcabf58
Revises: 1d50909c92f8
Create Date: 2025-10-20 03:13:49.907604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c501dcabf58'
down_revision: Union[str, Sequence[str], None] = '1d50909c92f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'item_stat_history', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_stat_history', type_='foreignkey')
    # ### end Alembic commands ###
