"""remove unit attributes

Revision ID: a42049cce734
Revises: a0161f90e409
Create Date: 2025-08-16 07:01:17.269815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42049cce734'
down_revision: Union[str, Sequence[str], None] = 'a0161f90e409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'unit')
    op.drop_column('storage_sections', 'total_units')
    op.drop_column('storage_sections', 'used_units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_sections', sa.Column('used_units', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('storage_sections', sa.Column('total_units', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
