"""Update Stat History Status to not Nullable

Revision ID: ace912da847b
Revises: 47a4bcfa95b9
Create Date: 2025-11-02 15:49:04.185605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ace912da847b'
down_revision: Union[str, Sequence[str], None] = '47a4bcfa95b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_stat_history', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_stat_history', 'stock_status',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='stockstatus'),
               nullable=True)
    # ### end Alembic commands ###
