"""Add Item Table

Revision ID: cfc7e062c18e
Revises: 1319a38b2604
Create Date: 2025-08-01 11:48:21.276092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfc7e062c18e'
down_revision: Union[str, Sequence[str], None] = '1319a38b2604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('PARTITION', 'LARGEITEM', name='itemtype'), nullable=False),
    sa.Column('measure_method', sa.Enum('VISION', 'WEIGHT', name='measuremethod'), nullable=True),
    sa.Column('item_weight', sa.Float(), nullable=True),
    sa.Column('partition_weight', sa.Float(), nullable=True),
    sa.Column('image', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
