"""Update Item Table with Additional Data

Revision ID: d694a5fc4005
Revises: a42049cce734
Create Date: 2025-09-13 06:02:10.510791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd694a5fc4005'
down_revision: Union[str, Sequence[str], None] = 'a42049cce734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('process', sa.String(length=50), nullable=False))
    op.add_column('items', sa.Column('tooling_used', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('vendor_pn', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('sap_pn', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('package_used', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_items_process'), 'items', ['process'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_process'), table_name='items')
    op.drop_column('items', 'package_used')
    op.drop_column('items', 'sap_pn')
    op.drop_column('items', 'vendor_pn')
    op.drop_column('items', 'tooling_used')
    op.drop_column('items', 'process')
    # ### end Alembic commands ###
